[package]
name = "yeap-borrow"
version = "1.0.0"
authors = []

[addresses]
yeap_borrow = "48583ed80aabb27c69dc9451a8a9553222040882bf07d7f88c6028087d877ca3"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.yeap-oracle]
local = "../yeap-oracle"

[dev-dependencies]
